
language: node_js

node_js:
  - "4"

cache:
  apt: true
  directories:
    - node_modules

addons:
  apt:
    packages:
      - graphicsmagick

env:
  - CXX=g++-4.8

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
  ssh_known_hosts: github.com
